---

- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: update apt-get
    apt: update_cache=yes cache_valid_time=36000

  - name: Install required packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - redis-server
      - python-selinux
      - nginx
      - supervisor
      - logrotate
      - python-pip

  - name: ensure supervisor conf.d directory exists
    file:
      path: /etc/supervisor/conf.d
      state: directory

  - name: ensure flask app log directory exists
    file:
      path: /var/log/adsnative
      state: directory

  - name: Copy supervisor configuration for flask
    template:
      src: supervisor.flask.j2
      dest: /etc/supervisor/conf.d/flask.conf

  - name: start the nginx service
    service: name=nginx state=started enabled=yes

  - name: Create the directories for site specific configurations
    file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
    with_items:
      - "sites-available"
      - "sites-enabled"

  - name: Copy the nginx configuration file
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

  - name: deleting the default configuration files under /etc/nginx/sites-available:sites-enabled
    file: path=/etc/nginx/{{ item }} state=absent
    with_items:
        - "sites-available/default"
        - "sites-enabled/default"

  - name: Copy the nginx default configuration file
    template: src=flask.conf.j2 dest=/etc/nginx/sites-available/flask.conf

  - name: Create the link for site enabled specific configurations
    file: path=/etc/nginx/sites-enabled/flask.conf state=link src=/etc/nginx/sites-available/flask.conf

  - name: changing the redis port to 1234
    lineinfile:
      dest: /etc/redis/redis.conf
      regexp: "^port"
      line: "port 1234"

  - name: install virtualenv version(15.1.0) with pip
    pip: name=virtualenv version=15.1.0

  - name: create virtualenv directory
    file : >
      path="/home/vagrant/webapps/adsnative"
      state="directory"
      owner="vagrant"
      group="vagrant"
      mode=0755

  - name: cloning the Flask App
    git:
      repo: https://github.com/picatcha/adsnative_devops_challenge.git
      dest: "/home/vagrant/webapps/adsnative"
      accept_hostkey: no
      recursive: yes
      force: yes

  - name: Copy requirements.txt file
    template:
      src: requirements.txt
      dest: "/home/vagrant/webapps/requirements.txt"
      owner: vagrant
      group: vagrant

  - name: installed specified python packages in virtualenv
    pip: requirements="/home/vagrant/webapps/requirements.txt" virtualenv="/home/vagrant/webapps/adsnative"

  - name: create logrotate directory
    file : >
      path="/etc/logrotate.d"
      state="directory"
      owner="root"
      group="root"
      mode=0755

  - name: create hourly rotate log file under /etc/logrotate.d
    template: src=logrotate.conf.j2 dest=/etc/logrotate.d/adsnative

  - name: create hourly rotate log file under /etc/cron.hourly
    template: src=logrotatehourly.conf.j2 dest=/etc/cron.hourly/logrotate

  - name: restart redis
    service: name=redis-server state=restarted

  - name: restart nginx
    service: name=nginx state=restarted

  - name: restart supervisor
    service: name=supervisor state=restarted

  - name: setting the timezone to US EST
    command: timedatectl set-timezone EST

  - name: updating the timezone
    command: ntpdate us.pool.ntp.org
  
